### ISSUE TITLE
I don't see it

### ISSUE THREAD

**Issue by rosecitysister** [philipnewcomer/Customizer-Framework#2]
I've installed the plugin but I see nothing in the admin panel. Am I doing something wrong? It says the plugin is active but there's nothing in the Customizer or anywhere that I can see.

ETA - I'm on WP version 4.0

**Comment by philipnewcomer** [comment]
Can you show the code that you are using to create your settings?

**Comment by rosecitysister** [comment]
I haven't created anything. I installed the plugin and there's nothing there. It says it is active but I don't see it. Can you tell me where it's supposed to be?

**Comment by philipnewcomer** [comment]
If you haven't created any options yet, there will be nothing for the framework to display. You will need to create some options first, as the [usage instructions](http://wordpress.org/plugins/customizer-framework/other_notes/) describe.

**Comment by rosecitysister** [comment]
Thank you Phillip - I had figured it out myself.  Sorry, I got caught up in something and forgot to update this ticket. Thank you!
